#!/bin/bash

if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "starting $DEV1/commands/run $*"
  set -x
fi

echo "cd $(pwd)"
echo "${BASH_SOURCE[0]})" "$@"
source "$DEV1_COMMANDS_PATH/utils/utilityFunctions"

source "$DEV1_COMMANDS_PATH/context" "$@"

if [[ "$?" == "1" ]]; then echo "DEV1 Error: Unable to resolve context"; return 1; fi

run1="$DEV1_TASK_PATH/run.bash"
run2="$DEV1_SUITE_PATH/project/run.bash"

if [[ -e "$run1" ]]; then
  runScript=$run1
elif [[ -e "$run2" ]]; then
  runScript="$run2"
else
  echo "Could not fine run.bash in either of"
  echo "    $run1"
  echo " or $run2"
  echo "you need to provide one"
  RETURN_OR_EXIT
fi

# shellcheck disable=SC2086
# shellcheck disable=SC2068
LogAction $runScript "$@"
source $runScript  "$@"
PrintActionLog
