#!/bin/bash

# if the suite is found, execute the build script in 
# the project_directory of the suitegiven in $1. 
# pass the entire list of command line parameters 
# and options to that script.

# Errors:
#   - Environment not set for DEV1
#   - Project not found among the suites
#   - Build script not found in the project
source $DEV1/commands/suite $1 $2 
for (( c=0; c<shift_params; c++ )); do 
  shift 
done
echo "pwd: $PWD"
if [[ -e build_parameters ]]; then
  build_parameters="$(cat build_parameters)"
fi
dev_dir=$(pwd)/${current_suite}dev
if [[ -e /build.sh ]]; then
  ./build.sh $@ $build_parameters
elif [[ -e $dev_dir/build.sh ]]; then
  cmd="$dev_dir/build.sh $@ $build_parameters"
  echo $cmd
  $cmd
else
 echo "Did not find a build.sh file in $pwd"
fi

