#!/bin/bash

# run visual studio code for the project

# Errors:
#   - Environment not set for DEV1
#   - Project not found among the suites
#   - Project code workspace not found
# Parameter sets:
# no-parameters: use previous task
# set -x #uncomment to debug
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "starting $DEV1/commands/ide $@"
  set -x
fi
source $DEV1_COMMANDS/context "$1" "$2" "$3"
if [[ "$?" == "1" ]]; then echo "DEV1 Error: Unable to resolve context"; return 1; fi
if [[ "$1" == "--" || "$2" == "--"  || "$3" == "--" || "$4" == "--" ]]; then
  while [[ ! "$1" == "--" ]]; do
    shift  # shift options before the --
  done
  shift    # shift the --
fi
if [[ "$current_task" == "" \
   && -e $DEV1_SUITES/$current_suite/repositories/$current_suite ]]; then
   cd $DEV1_SUITES/$current_suite/repositories/$current_suite
fi
echo "$(basename ${BASH_SOURCE[0]}) $@"
echo "cd $(pwd)"
if [[ -e $current_task.code-workspace ]]; then
  echo "code $current_task.code-workspace"
  code $current_task.code-workspace
elif [[ -e $current_suite.code-workspace ]]; then  
  echo "code $current_suite.code-workspace"
  code $current_suite.code-workspace
else
  echo "code ."
  code .
fi
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "ending   $DEV1/commands/run $@"
  set +x
fi