#!/bin/bash

# run visual studio code for the project

# Errors:
#   - Environment not set for DEV1
#   - Project not found among the suites
#   - Project code workspace not found
# Parameter sets:
# no-parameters: use previous task
# set -x #uncomment to debug

source $DEV1_COMMANDS/suite "$1" "$2" "$3"
echo $current_task
if [[ "$current_task" == "" \
   && -e $DEV1_SUITES/$current_suite/repositories/$current_suite ]]; then
   cd $DEV1_SUITES/$current_suite/repositories/$current_suite
fi
pwd
if [[ -e $current_task.code-workspace ]]; then
  echo "code $current_task.code-workspace"
  code $current_task.code-workspace
elif [[ -e $current_suite.code-workspace ]]; then  
  echo "code $current_suite.code-workspace"
  code $current_suite.code-workspace
else
  echo "code ."
  code .
fi