#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then RETURN_OR_EXIT="exit"; else RETURN_OR_EXIT="return"; fi

function cacheEnvVar(){
  echo "${!1} $(date)" >"$DEV1_CONTEXT_CACHE_PATH/${1}"
}
suiteName="$1"
if [[ "$suiteName" == "" ]];then  
  echo "You have to provide a suite/app name"; $RETURN_OR_EXIT; fi
if [[  "$suiteName" =~ [[:alnum:-]]*[^[:alnum:]]+ ]]; then 
  echo "$suiteName: A suite name including special characters or blanks is a bad idea";
  echo "Try something else"
  $RETURN_OR_EXIT; 
fi

if [[ ! -e "$DEV1_SUITES_PATH/${suiteName}" ]]; then
  export DEV1_SUITE_PATH="$DEV1_SUITES_PATH/${suiteName}"
  export DEV1_PROJECT_PATH="$DEV1_SUITE_PATH/project"
  export DEV1_REPOSITORIES_PATH="$DEV1_SUITE_PATH/repositories"
  export DEV1_WORKTREES_PATH="$DEV1_SUITE_PATH/worktrees"
  export DEV1_SUITE_NAME_NAME="${suiteName}"
  export DEV1_CONTEXT_CACHE_PATH="$HOME/.dev1"
  mkdir -p "$DEV1_CONTEXT_CACHE_PATH"
  mkdir -p "$DEV1_PROJECT_PATH"
  mkdir -p "$DEV1_REPOSITORIES_PATH"
  mkdir -p "$DEV1_WORKTREES_PATH"
  cacheEnvVar "DEV1_SUITE_NAME_PATH"

  export DEV1_SUITE_NAME=$suiteName
  export DEV1_TASK_NAME=""
  export DEV1_CODE_WORKSPACE_NAME=""

  export DEV1_SUITE_PATH=$suiteName
  export DEV1_TASK_PATH=""
  export DEV1_CODE_WORKSPACE_PATH=""
  if [[ ! -e "$DEV1_PROJECT_PATH/${suiteName}.config.json" ]]; then
    echo "{}" >"$DEV1_PROJECT_PATH/${suiteName}.config.json"
  fi
  if [[ -e "$DEV1_COMMANDS_PATH/maint" ]]; then
    source "$DEV1_COMMANDS_PATH/maint" "$@"
  else 
    cd  "$DEV1_PROJECT_PATH" || $RETURN_OR_EXIT
    code .
  fi
else
  echo "You already have a suite named $suiteName"
fi