#!/bin/bash

# if the project is found, execute the run script in 
# the project_directory of the project given in $1. 
# pass the entire list of command line parameters 
# and options to that script.

# Errors:
#   - Environment not set for DEV1
#   - Project not found among the suites
#   - run script not found in the project

if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "starting $DEV1/commands/run $@"
  set -x
fi
source $DEV1_COMMANDS/context "$1" "$2" 
if [[ "$1" == "$current_suite" ]]; then
  shift 1
fi
if [[  "$2" == "$current_task" ]]; then
  shift 1
fi
if [[ -e run.sh ]]; then
  ./run.sh  $@
else 
  run_script=$(find -L ./ -maxdepth 2 -name run_script.sh)
  if [[ ! "run_script" == "" ]]; then
    echo "$run_script $@"
    $run_script $@
  fi
fi
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "ending   $DEV1/commands/run $@"
  set +x
fi