#!/bin/bash
# source only
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "start /work/suites/dev1/worktrees/next/dev1/commands/suite"
  set -x
fi

source $DEV1_COMMANDS/context $1 $2

cd $DEV1_SUITES/${currentSuite}/tasks/${currentTask}

if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "end   /work/suites/dev1/worktrees/next/dev1/commands/suite"
  set +x
fi