#!/bin/bash
# source only

# shellcheck enable=require-variable-braces



# shellcheck disable=1091
source "${DEV1_COMMANDS_PATH}/context"  "$@"

cd "${DEV1_SUITES_PATH}/${DEV1_SUITE_NAME}/tasks/${DEV1_TASK_NAME}" || return 1
pwd