#!/bin/bash
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "start /work/suites/dev1/worktrees/next/dev1/commands/suite"
  set -x
fi

source $DEV1_COMMANDS/context
source $DEV1_COMMANDS/context $DEV1_SUITE $1

cd $DEV1_SUITES/$current_suite/tasks/$current_task
if [[ ! "$DEV1_DEBUG" == "" ]]; then
  echo "ending   $DEV1/commands/run $@"
  set +x
fi