#!/bin/bash
  # shellcheck disable=SC1091
declare -g state
declare -g _configJson
declare -g sourceforgeUsername
declare -g githubUsername
declare -g gitlabUsername

state="Starting 0020Config"
_startingPoint=$(pwd)
if [[ "$1" == "called" ]]; then
  shift
else
  source "$DEV1_COMMANDS_PATH/utils/utilityFunctions"
  source "$DEV1_PATH/maintenance/010Globals" "$1" reset
fi
# ------------------------------------------------------
GetConfigJson $1
# shellcheck disable=SC2034
state="Ending 020Config"
cd "$_startingPoint" || return 0
