#!/bin/bash
  # shellcheck disable=SC1091

state="Starting 060Tasks"
_startingPoint=$(pwd)
if [[ "$1" == "called" ]]; then
  shift
else
  source "$DEV1_COMMANDS_PATH/utils/utilityFunctions"
  source "$DEV1_PATH/maintenance/010Globals" "$1" reset
  source "$DEV1_PATH/maintenance/020Config" "$1"
  source "$DEV1_PATH/maintenance/022Suite" "called"
fi
# ------------------------------------------------------
source "$DEV1_PATH/maintenance/061GetTasks" called
declare -ga _tasksArray
declare -g _suiteName
declare -g _taskName
declare -g _title
  for ((it=0; it<${#_tasksArray[@]}; it += 1)); do

  _taskJson="${_tasksArray[$it]}"
    GetJsonString  _taskName    "$_taskJson" ".taskName"
    GetJsonString  _title    "$_taskJson" ".title"
    _taskPath="$DEV1_SUITES_PATH/${_suiteName}/tasks/${_taskName}"
    _mkdir   "$_taskPath"
    _mkdir   "$_taskPath/.vscode"
    if [[ "$_title" != "" && "$_title" != "null" ]]; then
      echo "$_title" >"$_taskPath/window.title"
      touch "$_taskPath/$_title"
    fi
done
# shellcheck disable=SC2034
state="Ending 060Tasks"
cd "$_startingPoint" || return 0
