#!/bin/bash
  # shellcheck disable=SC1091
declare -g _configJson
declare -ga _tasksArray
state="Starting 061GetTasks"
_startingPoint=$(pwd)

if [[ "$1" == "called" ]]; then
  shift
else
  source "$DEV1_COMMANDS_PATH/utils/utilityFunctions"
  source "$DEV1_PATH/maintenance/010Globals" "$1" reset
  source "$DEV1_PATH/maintenance/020Config" "$1"
  source "$DEV1_PATH/maintenance/022Suite" "called"
fi
# ------------------------------------------------------
declare -g unsetx
declare -g setx
$unsetx
if [[ "${#_tasksArray}" == "0" ]]; then
  GetJsonArray _tasksArray "${_configJson}" '.tasks[]'
  echo "${#_tasksArray[@]} tasks found"
fi
$setx
# -------------------------------------------

# shellcheck disable=SC2034
state="Ending 061GetTasks"
cd "$_startingPoint" || return 0