#!/bin/bash

#   urls assume you have a login  gitlab and have forked the osm repos there
#   and that you have an ssh key
#
source $DEV1_HELPERS/log_f 
user=callahanp
m="$DEV1_COMMANDS_PATH/app"
# set -x
$m  operation create \
    loglevel  LOG_LEVEL_FLOOD \
    suite fg-osm \
    origin git@gitlab.com:$user/fgosm.git \
    vscode default \
    branch next \
    \
    activity main \
    vscode c++ \
    \
    repository osm2Gear \
    branch ws3.0 \
    origin git@gitlab.com:$user/osm2gear.git \
    upstream git@gitlab.com:osm2city/osm2gear.git \
    activity   main \
    \
    repository osm2city \
    branch     master \
    origin git@gitlab.com:$user/osm2city.git \
    upstream git@gitlab.com:osm2city/osm2city.git \
    \
    repository   osm2city-data \
    branch       master \
    origin git@gitlab.com:callahanp/osm2city-data.git \
    upstream git@gitlab.com:osm2city/osm2city-data.git 
    

tree -L 3 $DEV1_SUITES/fg-osm